site_name: My Docs
theme:
  name: material
  palette:

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: red
      toggle: 
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode