site_name: My Docs
theme:
  name: material
  palette:

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: red
      toggle: 
        icon: material/brightness-4
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features: 
    - navigation.sections

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav: 
  - Notebook: 
    - Notebook/git.md
    - Notebook/docker.md
    - Notebook/HTML.md

  - Labs: 
    - Labs/ParrotOS for HTB.md

site_url: https://personal-site.sabonita.net/
repo_url: https://github.com/sabonita/personal-site
repo_name: sabonita/personal-site